[package]
name = "day1"
version.workspace = true
edition.workspace = true

[[bin]]
name = "part1"
path = "src/bin/part1.rs"

[[bin]]
name = "part2"
path = "src/bin/part2.rs"

[dependencies]
# Add day-specific dependencies here
